import 'dart:convert';

import 'package:dart_style/dart_style.dart';
import 'package:oche_codegen/src/model.dart';

final class SourceEmitter {
  const SourceEmitter();

  String emit(ApplicationModel application) {
    final out = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
      ..writeln('// Generated by package:oche_codegen.')
      ..writeln()
      ..writeln("import 'dart:io';")
      ..writeln();
    final imports = <String>{
      "import 'package:oche/oche_generated.dart' as oche_runtime;",
    };
    for (final controller in application.controllers) {
      imports.add(
        "import '${_escape(controller.libraryUri)}' as ${controller.importPrefix};",
      );
    }
    final sortedImports = imports.toList()..sort();
    out.writeln(sortedImports.join('\n'));
    out
      ..writeln()
      ..writeln('final class ${application.className}Oche {');
    for (final controller in application.controllers) {
      out.writeln(
        '  static final ${controller.fieldName} = '
        '${controller.importPrefix}.${controller.className}();',
      );
    }
    final controllerFields = application.controllers
        .map((controller) => controller.fieldName)
        .join(', ');
    final initializationParameters = List<String>.filled(
      application.controllers.length,
      'Object? _',
    ).join(', ');
    out
      ..writeln()
      ..writeln(
        '  static final oche_runtime.OcheDispatch _initializedDispatch = '
        '_initializeControllers($controllerFields);',
      )
      ..writeln()
      ..writeln(
        '  static oche_runtime.OcheDispatch _initializeControllers('
        '$initializationParameters) => _dispatch;',
      )
      ..writeln()
      ..writeln('  static Future<void> run({')
      ..writeln("    String host = '127.0.0.1',")
      ..writeln('    int port = 8080,')
      ..writeln('  }) => oche_runtime.runGeneratedApplication(')
      ..writeln("    name: '${_escape(application.className)}',")
      ..writeln('    dispatch: _initializedDispatch,')
      ..writeln('    host: host,')
      ..writeln('    port: port,')
      ..writeln('  );')
      ..writeln()
      ..writeln('  static void _dispatch(HttpRequest request) {')
      ..writeln(
        '    final segments = oche_runtime.ochePathSegments(request.uri);',
      )
      ..writeln('    if (segments == null) {')
      ..writeln('      oche_runtime.writeNotFound(request);')
      ..writeln('      return;')
      ..writeln('    }')
      ..writeln('    switch (segments.length) {');

    final byLength = <int, List<RouteModel>>{};
    for (final route in application.routes) {
      (byLength[route.segments.length] ??= <RouteModel>[]).add(route);
    }
    final lengths = byLength.keys.toList()..sort();
    for (final length in lengths) {
      final root = RouteTreeNode();
      for (final route in byLength[length]!) {
        _insert(root, route);
      }
      out.writeln('      case $length:');
      _writeNode(out, root, 0, 4);
    }
    out
      ..writeln('    }')
      ..writeln('    oche_runtime.writeNotFound(request);')
      ..writeln('  }')
      ..writeln('}');
    return DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
      lineEnding: '\n',
    ).format(out.toString());
  }

  void _insert(RouteTreeNode root, RouteModel route) {
    var node = root;
    for (final segment in route.segments) {
      if (segment.parameter) {
        node = node.parameter ??= RouteTreeNode();
      } else {
        node = node.literals.putIfAbsent(segment.value, RouteTreeNode.new);
      }
    }
    node.endpoints.add(route);
  }

  void _writeNode(
    StringBuffer out,
    RouteTreeNode node,
    int segmentIndex,
    int indent,
  ) {
    if (node.endpoints.isNotEmpty) {
      _writeLeaf(out, node.endpoints, indent);
      return;
    }
    final spaces = '  ' * indent;
    final literals = node.literals.entries.toList()
      ..sort((left, right) => left.key.compareTo(right.key));
    if (literals.isNotEmpty) {
      out.writeln('$spaces switch (segments[$segmentIndex]) {');
      for (final entry in literals) {
        out.writeln("$spaces  case '${_escape(entry.key)}':");
        _writeNode(out, entry.value, segmentIndex + 1, indent + 2);
      }
      out.writeln('$spaces}');
    }
    final parameter = node.parameter;
    if (parameter != null) {
      _writeNode(out, parameter, segmentIndex + 1, indent);
      return;
    }
    out
      ..writeln('${spaces}oche_runtime.writeNotFound(request);')
      ..writeln('$spaces return;');
  }

  void _writeLeaf(StringBuffer out, List<RouteModel> routes, int indent) {
    final spaces = '  ' * indent;
    final ordered = routes.toList()
      ..sort((left, right) => left.verb.index.compareTo(right.verb.index));
    out.writeln('$spaces switch (request.method) {');
    for (final route in ordered) {
      out.writeln("$spaces  case '${route.verb.wireName}':");
      _writeRoute(out, route, indent + 2);
      out.writeln('$spaces    return;');
    }
    final allow = ordered.map((route) => route.verb.wireName).toList();
    out
      ..writeln('$spaces  default:')
      ..writeln(
        '$spaces    oche_runtime.writeMethodNotAllowed(request, '
        '${_stringList(allow)});',
      )
      ..writeln('$spaces    return;')
      ..writeln('$spaces}');
  }

  void _writeRoute(StringBuffer out, RouteModel route, int indent) {
    final spaces = '  ' * indent;
    for (var index = 0; index < route.parameters.length; index++) {
      final parameter = route.parameters[index];
      final local = 'path$index';
      if (parameter.kind == PathValueKind.integer) {
        out
          ..writeln(
            '$spaces final $local = '
            'int.tryParse(segments[${parameter.segmentIndex}]);',
          )
          ..writeln('$spaces if ($local == null) {')
          ..writeln(
            "$spaces  oche_runtime.writeInvalidParameter(request, "
            "'${_escape(parameter.placeholder)}');",
          )
          ..writeln('$spaces  return;')
          ..writeln('$spaces}');
      } else {
        out.writeln(
          '$spaces final $local = segments[${parameter.segmentIndex}];',
        );
      }
    }
    final arguments = <String>[];
    for (var index = 0; index < route.parameters.length; index++) {
      final parameter = route.parameters[index];
      arguments.add(
        parameter.isNamed
            ? '${parameter.sourceName}: path$index'
            : 'path$index',
      );
    }
    final invocation =
        '${route.controller.fieldName}.${route.methodName}(${arguments.join(', ')})';
    switch (route.returnKind) {
      case HandlerReturnKind.string:
        out
          ..writeln('$spaces final result = $invocation;')
          ..writeln('$spaces oche_runtime.writeString(request, result);');
      case HandlerReturnKind.stringFuture:
        out.writeln(
          '$spaces oche_runtime.executeStringFuture(request, $invocation);',
        );
      case HandlerReturnKind.voidValue:
        out
          ..writeln('$spaces $invocation;')
          ..writeln('$spaces oche_runtime.writeNoContent(request);');
      case HandlerReturnKind.voidFuture:
        out.writeln(
          '$spaces oche_runtime.executeVoidFuture(request, $invocation);',
        );
      case HandlerReturnKind.bytes:
        out
          ..writeln('$spaces final result = $invocation;')
          ..writeln('$spaces oche_runtime.writeBytes(request, result);');
      case HandlerReturnKind.bytesFuture:
        out.writeln(
          '$spaces oche_runtime.executeBytesFuture(request, $invocation);',
        );
    }
  }

  String _stringList(List<String> values) =>
      'const [${values.map((value) => "'${_escape(value)}'").join(', ')}]';

  String _escape(String value) {
    final encoded = const JsonEncoder().convert(value);
    return encoded
        .substring(1, encoded.length - 1)
        .replaceAll("'", r"\'")
        .replaceAll(r'$', r'\$');
  }
}
