// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by package:oche_codegen.

import 'dart:io';

import 'package:hello_oche/application.dart' as i0;
import 'package:oche/oche_generated.dart' as oche_runtime;

final class ApplicationOche {
  static final _controller0 = i0.HelloController();
  static final _controller1 = i0.UserController();
  static final _controller2 = i0.AsyncController();
  static final _controller3 = i0.ErrorController();

  static final oche_runtime.OcheDispatch _initializedDispatch =
      _initializeControllers(
        _controller0,
        _controller1,
        _controller2,
        _controller3,
      );

  static oche_runtime.OcheDispatch _initializeControllers(
    Object? _,
    Object? _,
    Object? _,
    Object? _,
  ) => _dispatch;

  static Future<void> run({String host = '127.0.0.1', int port = 8080}) =>
      oche_runtime.runGeneratedApplication(
        name: 'Application',
        dispatch: _initializedDispatch,
        host: host,
        port: port,
      );

  static void _dispatch(HttpRequest request) {
    final segments = oche_runtime.ochePathSegments(request.uri);
    if (segments == null) {
      oche_runtime.writeNotFound(request);
      return;
    }
    switch (segments.length) {
      case 1:
        switch (segments[0]) {
          case 'hello':
            switch (request.method) {
              case 'GET':
                final result = _controller0.world();
                oche_runtime.writeString(request, result);
                return;
              default:
                oche_runtime.writeMethodNotAllowed(request, const ['GET']);
                return;
            }
        }
        oche_runtime.writeNotFound(request);
        return;
      case 2:
        switch (segments[0]) {
          case 'errors':
            switch (segments[1]) {
              case 'async':
                switch (request.method) {
                  case 'GET':
                    oche_runtime.executeStringFuture(
                      request,
                      _controller3.async(),
                    );
                    return;
                  default:
                    oche_runtime.writeMethodNotAllowed(request, const ['GET']);
                    return;
                }
              case 'sync':
                switch (request.method) {
                  case 'GET':
                    final result = _controller3.sync();
                    oche_runtime.writeString(request, result);
                    return;
                  default:
                    oche_runtime.writeMethodNotAllowed(request, const ['GET']);
                    return;
                }
            }
            oche_runtime.writeNotFound(request);
            return;
          case 'hello':
            switch (request.method) {
              case 'GET':
                final path0 = segments[1];
                oche_runtime.executeStringFuture(
                  request,
                  _controller0.greet(path0),
                );
                return;
              case 'POST':
                final path0 = segments[1];
                _controller0.accept(path0);
                oche_runtime.writeNoContent(request);
                return;
              default:
                oche_runtime.writeMethodNotAllowed(request, const [
                  'GET',
                  'POST',
                ]);
                return;
            }
          case 'users':
            switch (segments[1]) {
              case 'search':
                switch (request.method) {
                  case 'GET':
                    final result = _controller1.search();
                    oche_runtime.writeString(request, result);
                    return;
                  default:
                    oche_runtime.writeMethodNotAllowed(request, const ['GET']);
                    return;
                }
            }
            switch (request.method) {
              case 'GET':
                final path0 = int.tryParse(segments[1]);
                if (path0 == null) {
                  oche_runtime.writeInvalidParameter(request, 'id');
                  return;
                }
                final result = _controller1.find(path0);
                oche_runtime.writeString(request, result);
                return;
              case 'PUT':
                final path0 = int.tryParse(segments[1]);
                if (path0 == null) {
                  oche_runtime.writeInvalidParameter(request, 'id');
                  return;
                }
                oche_runtime.executeVoidFuture(
                  request,
                  _controller1.replace(path0),
                );
                return;
              case 'PATCH':
                final path0 = int.tryParse(segments[1]);
                if (path0 == null) {
                  oche_runtime.writeInvalidParameter(request, 'id');
                  return;
                }
                final result = _controller1.patch(path0);
                oche_runtime.writeBytes(request, result);
                return;
              case 'DELETE':
                final path0 = int.tryParse(segments[1]);
                if (path0 == null) {
                  oche_runtime.writeInvalidParameter(request, 'id');
                  return;
                }
                oche_runtime.executeBytesFuture(
                  request,
                  _controller1.delete(path0),
                );
                return;
              default:
                oche_runtime.writeMethodNotAllowed(request, const [
                  'GET',
                  'PUT',
                  'PATCH',
                  'DELETE',
                ]);
                return;
            }
        }
        oche_runtime.writeNotFound(request);
        return;
      case 3:
        switch (segments[0]) {
          case 'async':
            switch (segments[1]) {
              case 'sync':
                switch (request.method) {
                  case 'GET':
                    final path0 = int.tryParse(segments[2]);
                    if (path0 == null) {
                      oche_runtime.writeInvalidParameter(request, 'id');
                      return;
                    }
                    oche_runtime.executeStringFuture(
                      request,
                      _controller2.immediate(path0),
                    );
                    return;
                  default:
                    oche_runtime.writeMethodNotAllowed(request, const ['GET']);
                    return;
                }
            }
            oche_runtime.writeNotFound(request);
            return;
        }
        oche_runtime.writeNotFound(request);
        return;
    }
    oche_runtime.writeNotFound(request);
  }
}
