name: hello_oche
description: First real application built with the experimental public Oche API.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  oche: ^0.0.1

dev_dependencies:
  build_runner: ^2.16.0
  oche_codegen: ^0.0.1
